#!/bin/bash

DIRECTORY="/home/pslearner/Desktop"
FILE="$DIRECTORY/LabIsReady"

if [ -d "$DIRECTORY" ]; then
    sudo touch "$FILE"
    echo "File 'LabIsReady' has been created in the Desktop directory."
else
    echo "Directory $DIRECTORY does not exist."
    mkdir "$DIRECTORY"
    sudo touch "$FILE"
    echo "File 'LabIsReady' has been created in the Desktop directory."
fi
